import { useState, useEffect, useRef, useCallback } from 'react';
import { fetchApi } from '../api';
import { formatCost, formatDuration } from '../utils/format';

/* ── Types ──────────────────────────────────────────── */

interface Stats {
  totalSessions: number;
  totalTime: number;
  totalFiles: number;
  totalCommits: number;
  totalAICost: number;
  avgSessionTime: number;
  activeSessions: number;
}

interface ModelBreakdown {
  provider: string;
  model: string;
  totalCost: number;
  totalTokens: number;
  usageCount: number;
}

/* ── Canvas drawing helpers ─────────────────────────── */

const CARD_W = 720;
const CARD_H = 520;

function drawShareImage(stats: Stats, topModel: ModelBreakdown | null): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  const dpr = window.devicePixelRatio || 2;
  canvas.width = CARD_W * dpr;
  canvas.height = CARD_H * dpr;
  canvas.style.width = `${CARD_W}px`;
  canvas.style.height = `${CARD_H}px`;

  const ctx = canvas.getContext('2d')!;
  ctx.scale(dpr, dpr);

  // ── Background (Vercel/Linear style dark root)
  ctx.fillStyle = '#09090b'; // var(--bg-root)
  roundRect(ctx, 0, 0, CARD_W, CARD_H, 12);
  ctx.fill();

  // ── Branding (Subtle, neutral)
  ctx.fillStyle = '#a1a1aa'; // var(--text-secondary)
  ctx.font = '600 12px Inter, system-ui, sans-serif';
  ctx.letterSpacing = '1px';
  ctx.fillText('CODESESSION', 40, 50);
  ctx.letterSpacing = '0px';

  // ── Title
  ctx.fillStyle = '#fafafa'; // var(--text-primary)
  ctx.font = '600 28px Inter, system-ui, sans-serif';
  ctx.fillText('My AI Coding Stats', 40, 95);

  // ── Divider
  ctx.fillStyle = '#27272a'; // var(--border)
  ctx.fillRect(40, 120, CARD_W - 80, 1);

  // ── Stat grid (2 columns × 3 rows)
  const items: [string, string][] = [
    ['Sessions', String(stats.totalSessions)],
    ['Total Cost', formatCost(stats.totalAICost)],
    ['Total Time', formatDuration(stats.totalTime)],
    ['Files Changed', String(stats.totalFiles)],
    ['Commits', String(stats.totalCommits)],
    ['Avg Session', formatDuration(Math.round(stats.avgSessionTime))],
  ];

  const colW = 310;
  const startX = 40;
  const startY = 150;
  const rowH = 80;

  items.forEach(([label, value], i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = startX + col * colW;
    const y = startY + row * rowH;

    ctx.fillStyle = '#111113'; // var(--bg-surface)
    roundRect(ctx, x, y, 280, 64, 8);
    ctx.fill();
    
    ctx.strokeStyle = '#27272a'; // var(--border)
    ctx.lineWidth = 1;
    ctx.stroke();

    ctx.fillStyle = '#71717a'; // var(--text-tertiary)
    ctx.font = '500 11px Inter, system-ui, sans-serif';
    ctx.fillText(label.toUpperCase(), x + 16, y + 24);

    ctx.fillStyle = '#fafafa'; // var(--text-primary)
    ctx.font = '600 20px Inter, system-ui, sans-serif';
    ctx.fillText(value, x + 16, y + 50);
  });

  // ── Top model badge
  if (topModel) {
    const badgeY = startY + 3 * rowH + 10;
    
    ctx.fillStyle = '#111113'; // var(--bg-surface)
    roundRect(ctx, 40, badgeY, CARD_W - 80, 60, 8);
    ctx.fill();

    ctx.strokeStyle = '#27272a'; // var(--border)
    ctx.lineWidth = 1;
    ctx.stroke();

    ctx.fillStyle = '#a1a1aa'; // var(--text-secondary)
    ctx.font = '500 11px Inter, system-ui, sans-serif';
    ctx.fillText('⚡ TOP MODEL', 56, badgeY + 24);

    ctx.fillStyle = '#fafafa'; // var(--text-primary)
    ctx.font = '600 16px Inter, system-ui, sans-serif';
    const modelLabel = `${topModel.provider} / ${topModel.model}`;
    ctx.fillText(modelLabel, 56, badgeY + 45);

    ctx.fillStyle = '#a1a1aa'; // var(--text-secondary)
    ctx.font = '14px Inter, system-ui, sans-serif';
    const costLabel = formatCost(topModel.totalCost);
    ctx.textAlign = 'right';
    ctx.fillText(costLabel, CARD_W - 56, badgeY + 36);
    ctx.textAlign = 'left';
  }

  // ── Footer watermark
  ctx.fillStyle = '#52525b'; // var(--gray-600)
  ctx.font = '11px Inter, system-ui, sans-serif';
  ctx.textAlign = 'right';
  ctx.fillText('Generated by CodeSession', CARD_W - 40, CARD_H - 24);
  ctx.textAlign = 'left';

  return canvas;
}

function roundRect(
  ctx: CanvasRenderingContext2D,
  x: number, y: number, w: number, h: number, r: number,
) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}

/* ── Inline styles (scoped to this component) ──────── */

const styles = {
  preview: {
    position: 'relative' as const,
    width: CARD_W,
    maxWidth: '100%',
    margin: '0 auto',
    borderRadius: '12px',
    overflow: 'hidden' as const,
    background: 'var(--bg-root)',
    border: '1px solid var(--border)',
    boxShadow: '0 8px 24px rgba(0,0,0,0.5)',
  },
  previewGrid: {
    display: 'none',
  },
  previewGlow: {
    display: 'none',
  },
  inner: {
    position: 'relative' as const,
    zIndex: 1,
    padding: '40px 40px 32px',
  },
  brand: {
    fontSize: 12,
    fontWeight: 600,
    color: 'var(--text-secondary)',
    letterSpacing: 1,
    marginBottom: 8,
  },
  title: {
    fontSize: 28,
    fontWeight: 600,
    color: 'var(--text-primary)',
    margin: '0 0 16px',
    letterSpacing: '-0.02em',
  },
  divider: {
    height: 1,
    width: '100%',
    background: 'var(--border)',
    marginBottom: 28,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: 16,
  },
  statBox: {
    background: 'var(--bg-surface)',
    border: '1px solid var(--border)',
    borderRadius: 8,
    padding: '16px 20px',
  },
  statLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: 'var(--text-tertiary)',
    textTransform: 'uppercase' as const,
    letterSpacing: 0.5,
    marginBottom: 4,
  },
  statVal: {
    fontSize: 20,
    fontWeight: 600,
    color: 'var(--text-primary)',
    fontFamily: 'var(--font-mono, monospace)',
  },
  modelBadge: {
    marginTop: 20,
    padding: '16px 20px',
    borderRadius: 8,
    background: 'var(--bg-surface)',
    border: '1px solid var(--border)',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  modelLabel: {
    fontSize: 11,
    fontWeight: 500,
    color: 'var(--text-secondary)',
    marginBottom: 4,
    textTransform: 'uppercase' as const,
  },
  modelName: {
    fontSize: 16,
    fontWeight: 600,
    color: 'var(--text-primary)',
  },
  modelCost: {
    fontSize: 14,
    color: 'var(--text-secondary)',
    fontFamily: 'var(--font-mono, monospace)',
  },
  footer: {
    textAlign: 'right' as const,
    fontSize: 11,
    color: 'var(--gray-600)',
    marginTop: 16,
  },
  actions: {
    display: 'flex',
    justifyContent: 'center',
    gap: 12,
    marginTop: 24,
  },
  btn: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: 8,
    padding: '8px 16px',
    borderRadius: 6,
    border: '1px solid var(--border)',
    background: 'var(--bg-surface)',
    color: 'var(--text-primary)',
    fontSize: 13,
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'background 0.1s, border-color 0.1s',
  },
  btnPrimary: {
    background: 'var(--text-primary)',
    borderColor: 'var(--text-primary)',
    color: 'var(--bg-root)',
  },
} as const;

/* ── Component ──────────────────────────────────────── */

export default function ShareCard() {
  const [stats, setStats] = useState<Stats | null>(null);
  const [models, setModels] = useState<ModelBreakdown[]>([]);
  const [copied, setCopied] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  useEffect(() => {
    fetchApi<Stats>('/api/stats').then(setStats).catch(() => {});
    fetchApi<ModelBreakdown[]>('/api/model-breakdown').then(setModels).catch(() => {});
  }, []);

  const topModel = models.length > 0
    ? models.reduce((top, m) => (m.totalCost > top.totalCost ? m : top), models[0])
    : null;

  const handleDownload = useCallback(() => {
    if (!stats) return;
    const canvas = drawShareImage(stats, topModel);
    canvasRef.current = canvas;

    const link = document.createElement('a');
    link.download = 'codesession-stats.png';
    link.href = canvas.toDataURL('image/png');
    link.click();
  }, [stats, topModel]);

  const handleCopy = useCallback(async () => {
    if (!stats) return;
    const canvas = drawShareImage(stats, topModel);
    canvasRef.current = canvas;

    try {
      const blob = await new Promise<Blob | null>((resolve) =>
        canvas.toBlob(resolve, 'image/png'),
      );
      if (blob) {
        await navigator.clipboard.write([
          new ClipboardItem({ 'image/png': blob }),
        ]);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch {
      // Fallback: just download instead
      handleDownload();
    }
  }, [stats, topModel, handleDownload]);

  if (!stats) {
    return <div className="loading">Loading…</div>;
  }

  const statItems: [string, string][] = [
    ['Sessions', String(stats.totalSessions)],
    ['Total Cost', formatCost(stats.totalAICost)],
    ['Total Time', formatDuration(stats.totalTime)],
    ['Files Changed', String(stats.totalFiles)],
    ['Commits', String(stats.totalCommits)],
    ['Avg Session', formatDuration(Math.round(stats.avgSessionTime))],
  ];

  return (
    <div className="page">
      <div className="page-header">
        <h1 className="page-title">Share Your Stats</h1>
        <div className="page-subtitle">
          Generate a shareable image of your AI coding journey
        </div>
      </div>

      {/* Live preview card */}
      <div style={styles.preview}>
        <div style={styles.previewGrid} />
        <div style={styles.previewGlow} />

        <div style={styles.inner}>
          <div style={styles.brand}>CODESESSION</div>
          <h2 style={styles.title}>My AI Coding Stats</h2>
          <div style={styles.divider} />

          <div style={styles.grid}>
            {statItems.map(([label, value]) => (
              <div key={label} style={styles.statBox}>
                <div style={styles.statLabel}>{label}</div>
                <div style={styles.statVal}>{value}</div>
              </div>
            ))}
          </div>

          {topModel && (
            <div style={styles.modelBadge}>
              <div>
                <div style={styles.modelLabel}>⚡ TOP MODEL</div>
                <div style={styles.modelName}>
                  {topModel.provider} / {topModel.model}
                </div>
              </div>
              <div style={styles.modelCost}>{formatCost(topModel.totalCost)}</div>
            </div>
          )}

          <div style={styles.footer}>Generated by CodeSession</div>
        </div>
      </div>

      {/* Action buttons */}
      <div style={styles.actions}>
        <button
          style={{ ...styles.btn, ...styles.btnPrimary }}
          onClick={handleDownload}
        >
          <DownloadIcon />
          Download PNG
        </button>
        <button style={styles.btn} onClick={handleCopy}>
          {copied ? <CheckIcon /> : <CopyIcon />}
          {copied ? 'Copied!' : 'Copy as Image'}
        </button>
      </div>
    </div>
  );
}

/* ── Tiny inline icons for buttons ──────────────────── */

function DownloadIcon() {
  return (
    <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="currentColor"
      strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <path d="M7 10l5 5 5-5" />
      <path d="M12 15V3" />
    </svg>
  );
}

function CopyIcon() {
  return (
    <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="currentColor"
      strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <rect x={9} y={9} width={13} height={13} rx={2} />
      <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    </svg>
  );
}

function CheckIcon() {
  return (
    <svg width={16} height={16} viewBox="0 0 24 24" fill="none" stroke="currentColor"
      strokeWidth={2} strokeLinecap="round" strokeLinejoin="round">
      <path d="M20 6L9 17l-5-5" />
    </svg>
  );
}
